import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MultipleLocator


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot the MF Fig. 3d cavity-loss sweep generated by generate_kappa_sweep.py."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).resolve().parent / "kappa_sweep" / "kappa_sweep_summary.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent / "kappa_sweep" / "Fig3d_kappa_sweep.pdf",
    )
    parser.add_argument("--show-maxima", action="store_true", help="Draw vertical lines at each curve maximum.")
    parser.add_argument("--show", action="store_true", help="Display the plot window.")
    return parser.parse_args()


def main():
    args = parse_args()
    with args.input.open("r", newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError(f"No data found in {args.input}")
    data = {
        "nu_eV": np.array([float(row["nu_eV"]) for row in rows]),
        "kappa_ratio": np.array([float(row["kappa_ratio"]) for row in rows]),
        "omega_rabi_eV": np.array([float(row["omega_rabi_eV"]) for row in rows]),
        "Evib_per_molecule_g_avg_eV": np.array([float(row["Evib_per_molecule_g_avg_eV"]) for row in rows]),
    }

    plt.rcParams["mathtext.fontset"] = "stix"
    plt.rcParams["mathtext.default"] = "regular"
    fig, ax = plt.subplots(figsize=(7.2, 5.2), dpi=160)

    kappa_values = sorted(np.unique(data["kappa_ratio"]))
    cmap = plt.get_cmap("turbo")
    if len(kappa_values) == 1:
        colors = ["black"]
    else:
        colors = [cmap(i / (len(kappa_values) - 1)) for i in range(len(kappa_values))]

    omega_rabi_eV = float(data["omega_rabi_eV"][0])
    ax.axvline(
        omega_rabi_eV,
        color="0.45",
        linestyle="--",
        linewidth=1.3,
        alpha=0.9,
        label=r"$\nu=\Omega$",
        zorder=1,
    )

    for color, kappa_ratio in zip(colors, kappa_values):
        mask = np.isclose(data["kappa_ratio"], kappa_ratio)
        order = np.argsort(data["nu_eV"][mask])
        nu_vals = data["nu_eV"][mask][order]
        evib_vals = data["Evib_per_molecule_g_avg_eV"][mask][order]
        ax.plot(
            nu_vals,
            evib_vals,
            color=color,
            linewidth=2.0,
            label=rf"$\kappa/\Omega={kappa_ratio:.1f}$",
            zorder=3,
        )
        if args.show_maxima:
            peak_idx = int(np.argmax(evib_vals))
            ax.axvline(
                nu_vals[peak_idx],
                color="0.7",
                linestyle=":",
                linewidth=1.0,
                alpha=0.9,
                zorder=2,
            )

    ax.set_xlabel(r"$\nu$ (eV)", fontsize=16)
    ax.set_ylabel(r"$\langle E_{\mathrm{vib,g}}\rangle$ (eV)", fontsize=16)
    ax.set_xlim(data["nu_eV"].min(), data["nu_eV"].max())
    ymax = 1.05 * data["Evib_per_molecule_g_avg_eV"].max()
    ax.set_ylim(0.0, ymax if ymax > 0 else 1.0)

    x_range = ax.get_xlim()[1] - ax.get_xlim()[0]
    x_major = x_range / 6.0
    ax.xaxis.set_major_locator(MultipleLocator(x_major))
    ax.xaxis.set_minor_locator(MultipleLocator(x_major / 4.0))
    ax.tick_params(direction="in", which="both", labelsize=13)
    ax.tick_params(axis="x", which="major", length=7)
    ax.tick_params(axis="x", which="minor", length=4)
    ax.tick_params(axis="y", which="major", length=7)
    ax.tick_params(axis="y", which="minor", length=4)
    ax.grid(alpha=0.2, linewidth=0.7)

    ax.legend(loc="upper right", frameon=True, fontsize=11)
    fig.tight_layout()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output, bbox_inches="tight")

    if args.show:
        plt.show()
    else:
        plt.close(fig)


if __name__ == "__main__":
    main()
